version: '3.1'

services:  # Servicios

  wordpress:  # Servicio
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - /home/ubuntu/environment/datos/wordpress:/var/www/html

  db:       # Servicio BBDD    <--- Nombre DNS
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /home/ubuntu/environment/datos/mysql:/var/lib/mysql

---







